name: spaceship
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # backbone
  rxdart: ^0.27.7
  dio: ^5.0.1
  multiple_result: ^4.0.0
  go_router: ^6.5.6
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  intl: ^0.18.0
  sprintf: ^7.0.0
  # get_it:
  #   git: https://github.com/fluttercommunity/get_it.git

  # UI
  font_awesome_flutter: ^10.1.0
  animated_toggle_switch: ^0.6.1
  loading_indicator: ^3.1.0
  logger: ^1.3.0
  cached_network_image: ^3.2.3
  syncfusion_flutter_calendar: ^21.1.39

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
